project:
  name: Pythia's Advice
  department: EAISI
data_dir: ./data
environment: production

csv_file_spec:
  delim: ;
  header: no
  date_format: '%Y-%m-%d'

sales:
  details:
    file_pattern: ^DD_SALES_QTY_202[12345].*\.csv$
